Add city selection + userDefaults for them + change background color …
TonikYoung/MyWeatherApp pull request #11
Opened 2024-06-26 09:40 UTC by TonikYoung

…method to assets colors

2024-06-26 19:28 UTC, MariaKulkova requested changes

2024-06-26 19:28 UTC, MariaKulkova commented on MyWeatherApp/Models/CitySelectionViewModel.swift
> +    init() {
Обрати внимание на конвенцию Code Style в сортировке методов:
- сначала конструктор
- потом неприватные методы
- потом приватные методы

2024-06-26 19:28 UTC, MariaKulkova commented on MyWeatherApp/Models/CitySelectionViewModel.swift
> +        let citiesData = try! PropertyListEncoder().encode(cities)
try! - это краш в продакшене. При этом есть высокая вероятность, что что-то не декодируется
Ошибки нужно обрабатывать через конструкцию. В случае успех сохранять, в случае ошибки - можно пока ошибку просто вывести в консоль через print

```swift
do {
}
catch {
}
```

2024-06-26 19:28 UTC, MariaKulkova commented on MyWeatherApp/Models/CitySelectionViewModel.swift
> +        UserDefaults.standard.set(citiesData, forKey: "cityName")
Давай из UserDefaults сделаем проперти класса. Это внешняя зависимость

2024-06-26 19:28 UTC, MariaKulkova commented on MyWeatherApp/Models/CitySelectionViewModel.swift
> +        let fetchedCities = try! PropertyListDecoder().decode([CityItem].self, from: fetchedData)
Force unwrap нужно убирать: разворачивать optional, использовать guard, do-catch в общем любые конструкции, чтобы приложение не крашилось, если мы можем предсказуемо обработать проблему

2024-06-26 19:28 UTC, MariaKulkova commented on MyWeatherApp/Models/CitySelectionViewModel.swift
>          cities.remove(atOffsets: index)
А при удалении не нужно из UserDefault удалить тоже?

2024-06-26 19:28 UTC, MariaKulkova commented on MyWeatherApp/Functions/BackgroundColor.swift
> +    var backgroundColor = Color(UIColor(named: "BaseViewColor")!)
У Color тоже есть конструктор с именем: **https://developer.apple.com/documentation/swiftui/color/init(_:bundle:)**

2024-06-26 19:28 UTC, MariaKulkova commented on MyWeatherApp/Functions/BackgroundColor.swift
> +    var backgroundColor = Color(UIColor(named: "BaseViewColor")!)
Давай напишем extension к Color с функцией, которая будет принимать название цвета, и если цвет есть в каталоге, то возвращать его. А если цвета нет, то дефолтный или fatalError (будем крашиться в разработке)
Тогда можно будет использовать `Color("BaseViewColor")` без force unwrap

2024-06-26 19:28 UTC, MariaKulkova commented on MyWeatherApp/Models/CitySelectionViewModel.swift
> +        UserDefaults.standard.set(citiesData, forKey: "cityName")
ключ cityName больше не соответствует содержимому, там же теперь массив городов

2024-06-26 19:28 UTC, MariaKulkova commented on MyWeatherApp/Models/CitySelectionViewModel.swift
>          let newCity = CityItem(cityName: name)
cityName выглядит избыточно, уже есть City в названии самой структуры, поэтому атрибут можно называть просто name

2024-06-27 06:47 UTC, TonikYoung commented on MyWeatherApp/Models/CitySelectionViewModel.swift
> +    init() {
Поправил

2024-06-27 06:48 UTC, TonikYoung commented on MyWeatherApp/Models/CitySelectionViewModel.swift
> +        let citiesData = try! PropertyListEncoder().encode(cities)
Поправил

2024-06-27 06:53 UTC, TonikYoung commented on MyWeatherApp/Models/CitySelectionViewModel.swift
> +        let fetchedCities = try! PropertyListDecoder().decode([CityItem].self, from: fetchedData)
Поправил

2024-06-27 07:03 UTC, TonikYoung commented on MyWeatherApp/Models/CitySelectionViewModel.swift
>          cities.remove(atOffsets: index)
Поправил

2024-06-27 07:43 UTC, TonikYoung commented on MyWeatherApp/Models/CitySelectionViewModel.swift
> +        UserDefaults.standard.set(citiesData, forKey: "cityName")
Поменял

2024-06-27 07:45 UTC, TonikYoung commented on MyWeatherApp/Models/CitySelectionViewModel.swift
>          let newCity = CityItem(cityName: name)
Поменял

2024-06-27 08:27 UTC, TonikYoung commented on MyWeatherApp/Functions/BackgroundColor.swift
> +    var backgroundColor = Color(UIColor(named: "BaseViewColor")!)
Сделал

2024-06-28 13:45 UTC, MariaKulkova commented on MyWeatherApp/Functions/BackgroundColor.swift
> +    }
`Color(colorName)`

2024-06-28 13:45 UTC, MariaKulkova commented on MyWeatherApp/Functions/BackgroundColor.swift
> +    }
```swift
else {
    .gray
}
```

2024-06-28 14:02 UTC, MariaKulkova approved these changes

2024-06-28 14:04 UTC, merged